"""Python-side utilities for generating Julia source code from sympy expressions.

Typical usage
-------------
1. Compute psi_fH via :func:`chebyshev_filter.apply_f_of_H_on_psi`.
2. Extract envelopes with :func:`chebyshev_filter.extract_cos_sin_coeffs`.
3. Group by Gaussian factor: :func:`chebyshev_filter.group_by_exp_combined`.
4. Apply Horner form: :func:`chebyshev_filter.apply_horner`.
5. Call :func:`build_julia_batch_script` to get a complete standalone ``.jl``.
6. Call ``julia script.jl grid.bin kvals.bin out.bin N n_waves`` to evaluate.

Legacy: :func:`build_julia_scalar_function` + :func:`build_julia_benchmark_script`
build a scalar function + standalone benchmark (useful for timing a single point).
"""

import sympy as sp

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _jl(expr):
    """Convert sympy expression to Julia code, stripping broadcast operators."""
    s = sp.julia_code(expr)
    # sp.julia_code may emit .+, .*, etc. for some expressions; strip the dots
    # so the code is valid for scalar evaluation.
    for op in ('.+', '.-', '.*', './', '.^'):
        s = s.replace(op, op[1:])
    return s


def expr_to_julia_code(expr):
    """Convert a single sympy expression to a Julia code string."""
    return _jl(expr)


def build_julia_scalar_function(terms_cos, terms_sin, func_name='f_psi'):
    """Build a Julia function that evaluates f(H)*psi at a single grid point.

    The generated function computes
        f_psi(x,y,z,kx,ky,kz,b)
          = (Σ_i exp_i(x,y,z) * poly_i(x,y,z,kx,ky,kz)) * cos(kx*x+ky*y+kz*z+b)
          + (Σ_j exp_j(x,y,z) * poly_j(x,y,z,kx,ky,kz)) * sin(kx*x+ky*y+kz*z+b)

    Parameters
    ----------
    terms_cos, terms_sin : list of (exp_part, poly_part)
        Output of :func:`chebyshev_filter.group_by_exp_combined`
        (optionally post-processed with :func:`chebyshev_filter.apply_horner`).
    func_name : str

    Returns
    -------
    str  Julia source code
    """
    lines = [f'function {func_name}(x::Float64, y::Float64, z::Float64,',
             f'                    kx::Float64, ky::Float64, kz::Float64,',
             f'                    b::Float64)::Float64']

    cos_vars = []
    for i, (ep, pp) in enumerate(terms_cos):
        var = f'_ccos{i}'
        lines.append(f'    {var} = ({_jl(ep)}) * ({_jl(pp)})')
        cos_vars.append(var)

    sin_vars = []
    for i, (ep, pp) in enumerate(terms_sin):
        var = f'_csin{i}'
        lines.append(f'    {var} = ({_jl(ep)}) * ({_jl(pp)})')
        sin_vars.append(var)

    phase   = 'kx*x + ky*y + kz*z + b'
    cos_sum = ' + '.join(cos_vars) if cos_vars else '0.0'
    sin_sum = ' + '.join(sin_vars) if sin_vars else '0.0'
    lines.append(f'    return ({cos_sum}) * cos({phase}) + ({sin_sum}) * sin({phase})')
    lines.append('end')
    return '\n'.join(lines)


def build_julia_batch_script(terms_cos, terms_sin, func_name='f_psi'):
    """Generate a complete standalone Julia script for batch grid evaluation.

    The script reads binary input files, evaluates f(H)*psi for every
    plane wave on the 3-D grid, and writes a binary output file.  It
    requires **no Julia packages** beyond the standard library.

    Call convention (from the command line or subprocess)::

        julia eval_filter.jl grid.bin kvals.bin out.bin N n_waves

    where

    * ``grid.bin``  – flat float64 array ``[X_flat; Y_flat; Z_flat]``
                      (3 × N float64 values, little-endian)
    * ``kvals.bin`` – flat float64 array ``[kx0,ky0,kz0,b0, kx1,…]``
                      (4 × n_waves float64 values)
    * ``out.bin``   – output: ``n_waves × N`` float64 values
                      (wave-major order, same layout as C_f.ravel())
    * ``N``         – total grid points (= Ng³)
    * ``n_waves``   – number of plane waves

    Parameters
    ----------
    terms_cos, terms_sin : list of (exp_part, poly_part)
        From :func:`chebyshev_filter.group_by_exp_combined`, optionally
        post-processed with :func:`chebyshev_filter.apply_horner`.
    func_name : str

    Returns
    -------
    str  Complete Julia source ready to write to a ``.jl`` file.
    """
    scalar_src = build_julia_scalar_function(terms_cos, terms_sin,
                                             func_name=func_name)
    return f"""\
# Auto-generated by symbolic_code.julia_codegen — DO NOT EDIT
# Evaluates the Chebyshev-filtered plane-wave basis on a 3-D grid.
#
# Usage:
#   julia eval_filter.jl grid.bin kvals.bin out.bin N n_waves

{scalar_src}

function main()
    length(ARGS) == 5 || error(
        "Usage: julia eval_filter.jl grid.bin kvals.bin out.bin N n_waves")

    grid_file  = ARGS[1]
    kvals_file = ARGS[2]
    out_file   = ARGS[3]
    N          = parse(Int, ARGS[4])
    n_waves    = parse(Int, ARGS[5])

    # Read flat grid arrays X, Y, Z (each N Float64 values)
    buf = Vector{{Float64}}(undef, 3 * N)
    open(grid_file, "r") do io; read!(io, buf); end
    X = @view buf[1:N]
    Y = @view buf[N+1:2N]
    Z = @view buf[2N+1:3N]

    # Read k/b values: kx0,ky0,kz0,b0, kx1,...
    kb = Vector{{Float64}}(undef, 4 * n_waves)
    open(kvals_file, "r") do io; read!(io, kb); end

    # Evaluate and collect output
    out = Vector{{Float64}}(undef, n_waves * N)
    for iw in 0:n_waves-1
        kx_v = kb[4*iw+1]
        ky_v = kb[4*iw+2]
        kz_v = kb[4*iw+3]
        b_v  = kb[4*iw+4]
        @inbounds for i in 1:N
            out[iw*N + i] = {func_name}(X[i], Y[i], Z[i], kx_v, ky_v, kz_v, b_v)
        end
    end

    open(out_file, "w") do io; write(io, out); end
end

main()
"""


def build_julia_benchmark_script(julia_func_src, n_points=10_000, n_iter=40):
    """Wrap a Julia function in a simple benchmark harness.

    Parameters
    ----------
    julia_func_src : str
        Output of :func:`build_julia_scalar_function`.
    n_points : int
        Number of random evaluation points.
    n_iter : int
        Number of timing iterations.

    Returns
    -------
    str  Complete Julia script ready to run with ``julia script.jl``.
    """
    return f"""\
# Auto-generated Julia benchmark script
{julia_func_src}

using Random
Random.seed!(42)
n = {n_points}
xs = randn(n); ys = randn(n); zs = randn(n)
kx0 = 1.0; ky0 = 0.0; kz0 = 0.0; b0 = 0.0

result = similar(xs)
println("Warming up ...")
for i in 1:n
    result[i] = f_psi(xs[i], ys[i], zs[i], kx0, ky0, kz0, b0)
end

println("Benchmarking ({n_iter} iterations x $n points) ...")
@time begin
    for _ in 1:{n_iter}
        for i in 1:n
            result[i] = f_psi(xs[i], ys[i], zs[i], kx0, ky0, kz0, b0)
        end
    end
end
GC.gc()
println("Done.")
"""
