#!/usr/bin/env python3
"""count_julia_nop.py

Count single-grid-point arithmetic operations (Nop) in Julia filter .jl files
generated by symbolic_code.julia_codegen.

What is counted
---------------
For each grid point processed by eval_one_wave!, Nop is the total number of
arithmetic operations:

  add_sub     — binary + / - in scalar expressions (unary minus not counted)
  mul_div     — * and /
  pow         — ^
  math_calls  — recognised transcendental function calls: exp, log, sin, cos,
                 sqrt, abs, … (see SCALAR_MATH_FUNCS below)
  Nop         = add_sub + mul_div + pow + math_calls (total)

Lines counted
-------------
  • All @inline function bodies  (called once per (point, wave))
  • eval_one_wave! body, including @. vectorised lines (phase, cos, sin)
    — each point still pays one scalar evaluation of these expressions

Lines excluded
--------------
  • main() function body and the standalone main() call
  • Function / block signature lines, end keywords, comments

Usage
-----
  # Single file
  python count_julia_nop.py julia_filter_m10_a0p046511628_bm1p3255814.jl

  # Multiple files
  python count_julia_nop.py julia_filter_m10_*.jl julia_filter_m12_*.jl

  # Glob pattern (passed as string, Python expands internally)
  python count_julia_nop.py --glob "julia_filter_m*.jl"

  # Save results to JSON
  python count_julia_nop.py julia_filter_m*.jl --json nop_summary.json

  # Show per-line breakdown
  python count_julia_nop.py julia_filter_m10_*.jl --verbose

  # CSV table to stdout
  python count_julia_nop.py julia_filter_m*.jl --csv
"""

from __future__ import annotations

import argparse
import glob as glob_module
import json
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Recognised scalar math function calls
# ---------------------------------------------------------------------------
SCALAR_MATH_FUNCS: frozenset[str] = frozenset({
    'exp', 'exp2', 'expm1',
    'log', 'log2', 'log10', 'log1p',
    'sin', 'cos', 'tan',
    'asin', 'acos', 'atan', 'atan2',
    'sinh', 'cosh', 'tanh',
    'sqrt', 'cbrt', 'hypot',
    'abs', 'sign', 'floor', 'ceil', 'round',
    'muladd', 'fma',
})

# Token kinds whose presence makes the NEXT +/- binary (not unary)
_VALUE_KINDS: frozenset[str] = frozenset({'number', 'ident', 'rparen', 'rbracket'})

# Julia syntax keywords that are NOT value-producing (preceding +/- is unary)
_NON_VALUE_KEYWORDS: frozenset[str] = frozenset({
    'return', 'local', 'const', 'global', 'in',
    'if', 'else', 'elseif', 'while', 'for', 'begin',
    'function', 'macro', 'struct', 'mutable', 'abstract',
    'import', 'using', 'export', 'module',
    'do', 'try', 'catch', 'finally', 'throw',
})

# Block-opening keywords that increase nesting depth
_BLOCK_OPEN = re.compile(
    r'^\s*(?:@\w+\s+)*'
    r'(?:function|for|if|while|begin|let|try|quote)\b'
)
_FUNC_NAME = re.compile(r'^\s*(?:@\w+\s+)*function\s+(\w+)')
_BLOCK_END  = re.compile(r'^\s*end\s*$')

# Comment in file header recording pre-computed op count
_COMMENT_OPS = re.compile(r'#\s*total_ops\s*=\s*(\d+)')

# Param metadata from the file header (set by build_julia_Hn_snippet)
_META_M   = re.compile(r'Polynomial order.*?m\s*=\s*(\d+)', re.IGNORECASE)
_META_A   = re.compile(r'[,\s]a\s*=\s*([-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?\d+)?)')
_META_B   = re.compile(r'[,\s]b\s*=\s*([-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?\d+)?)')


# ---------------------------------------------------------------------------
# Tokeniser
# ---------------------------------------------------------------------------

def _tokenize(line: str):
    """Yield (kind, value) tokens for one expression line.

    Kinds: 'ident', 'number', 'op', 'lparen', 'rparen', 'lbracket', 'rbracket',
           'other'.
    """
    i, n = 0, len(line)
    while i < n:
        c = line[i]
        if c in ' \t':
            i += 1
            continue
        if c.isalpha() or c == '_':
            j = i + 1
            while j < n and (line[j].isalnum() or line[j] in '_!'):
                j += 1
            yield ('ident', line[i:j])
            i = j
        elif c.isdigit() or (c == '.' and i + 1 < n and line[i + 1].isdigit()):
            j = i + 1
            while j < n and (line[j].isdigit() or line[j] == '.'):
                j += 1
            if j < n and line[j] in 'eE':
                j += 1
                if j < n and line[j] in '+-':
                    j += 1
                while j < n and line[j].isdigit():
                    j += 1
            yield ('number', line[i:j])
            i = j
        elif c in '+-*/^':
            yield ('op', c)
            i += 1
        elif c == '(':
            yield ('lparen', c); i += 1
        elif c == ')':
            yield ('rparen', c); i += 1
        elif c == '[':
            yield ('lbracket', c); i += 1
        elif c == ']':
            yield ('rbracket', c); i += 1
        else:
            yield ('other', c); i += 1


# ---------------------------------------------------------------------------
# Per-line op counter
# ---------------------------------------------------------------------------

def count_ops_in_line(line: str) -> dict:
    """Count arithmetic operations in a single Julia code line.

    Returns dict with keys: add_sub, mul_div, pow, calls (dict fname→count).
    """
    # Strip inline comment
    ci = line.find('#')
    if ci >= 0:
        line = line[:ci]
    line = line.strip()
    if not line:
        return {'add_sub': 0, 'mul_div': 0, 'pow': 0, 'calls': {}}

    tokens = list(_tokenize(line))
    add_sub = mul_div = pow_n = 0
    calls: dict[str, int] = {}

    for idx, (kind, val) in enumerate(tokens):
        if kind == 'op':
            if val in '+-':
                # Binary only when preceded by a value-producing token
                if idx > 0:
                    pk, pv = tokens[idx - 1]
                    if pk in _VALUE_KINDS and not (pk == 'ident' and pv in _NON_VALUE_KEYWORDS):
                        add_sub += 1
            elif val in '*/':
                mul_div += 1
            elif val == '^':
                pow_n += 1
        elif kind == 'ident' and val in SCALAR_MATH_FUNCS:
            # Check followed immediately by '(' (no spaces after tokenising)
            if idx + 1 < len(tokens) and tokens[idx + 1][0] == 'lparen':
                calls[val] = calls.get(val, 0) + 1

    return {'add_sub': add_sub, 'mul_div': mul_div, 'pow': pow_n, 'calls': calls}


# ---------------------------------------------------------------------------
# File analyser
# ---------------------------------------------------------------------------

def analyze_file(path: Path, verbose: bool = False) -> dict:
    """Parse a Julia filter .jl file and return Nop statistics.

    Parameters
    ----------
    path    : Path to the .jl file.
    verbose : If True, include per-line breakdown in result.

    Returns
    -------
    dict with keys:
      file, m, a, b,
      add_sub, mul_div, pow, math_calls (dict), n_math_calls,
      Nop,
      total_ops_comment (int or None — from '# total_ops=N' header if present)
    """
    source = path.read_text(errors='replace')
    lines  = source.splitlines()

    # ── extract header metadata ───────────────────────────────────────────────
    header = '\n'.join(lines[:20])
    m_val  = int(_META_M.search(header).group(1)) if _META_M.search(header) else None
    a_val  = float(_META_A.search(header).group(1)) if _META_A.search(header) else None
    b_val  = float(_META_B.search(header).group(1)) if _META_B.search(header) else None

    # Also try filename: julia_filter_m10_a0p046511628_bm1p3255814.jl
    fn_m = re.search(r'_m(\d+)_', path.name)
    fn_a = re.search(r'_a([\d]+p[\d]+)(?:_|\.)', path.name)
    fn_b = re.search(r'_b(m?[\d]+p[\d]+)(?:_|\.)', path.name)
    if m_val is None and fn_m:
        m_val = int(fn_m.group(1))
    if a_val is None and fn_a:
        a_val = float(fn_a.group(1).replace('p', '.'))
    if b_val is None and fn_b:
        raw_b = fn_b.group(1)
        if raw_b.startswith('m'):
            b_val = -float(raw_b[1:].replace('p', '.'))
        else:
            b_val = float(raw_b.replace('p', '.'))

    # total_ops comment (CSE scripts only)
    top_comment = next(
        (int(m.group(1)) for line in lines[:30]
         if (m := _COMMENT_OPS.search(line))),
        None,
    )

    # ── scope tracking ────────────────────────────────────────────────────────
    # Skip only the main() function body and the standalone main() call.
    # Count everything else (all @inline functions and eval_one_wave!).
    depth      = 0
    skip_depth = None   # set to depth when we enter main()

    totals: dict = {'add_sub': 0, 'mul_div': 0, 'pow': 0, 'calls': {}}
    verbose_rows: list[tuple] = []

    for lineno, raw in enumerate(lines, 1):
        stripped = raw.strip()

        # blank / comment
        if not stripped or stripped.startswith('#'):
            continue

        # ── block-open detection ──────────────────────────────────────────────
        if _BLOCK_OPEN.match(stripped):
            depth += 1
            m_fn = _FUNC_NAME.match(stripped)
            if m_fn and m_fn.group(1) == 'main' and skip_depth is None:
                skip_depth = depth
            # Don't count the signature line itself
            continue

        # ── block-end detection ───────────────────────────────────────────────
        if _BLOCK_END.match(stripped):
            if skip_depth is not None and depth == skip_depth:
                skip_depth = None
            depth = max(depth - 1, 0)
            continue

        # standalone `main()` call (top level, outside any function)
        if depth == 0 and re.match(r'^main\(\s*\)\s*$', stripped):
            continue

        # skip main() body
        if skip_depth is not None:
            continue

        # ── count ops ─────────────────────────────────────────────────────────
        ops = count_ops_in_line(stripped)
        n_line = (ops['add_sub'] + ops['mul_div'] + ops['pow']
                  + sum(ops['calls'].values()))

        totals['add_sub'] += ops['add_sub']
        totals['mul_div'] += ops['mul_div']
        totals['pow']     += ops['pow']
        for fn, cnt in ops['calls'].items():
            totals['calls'][fn] = totals['calls'].get(fn, 0) + cnt

        if verbose and n_line > 0:
            verbose_rows.append((lineno, ops, stripped))

    n_calls = sum(totals['calls'].values())
    nop     = totals['add_sub'] + totals['mul_div'] + totals['pow'] + n_calls

    result: dict = {
        'file'             : str(path),
        'm'                : m_val,
        'a'                : a_val,
        'b'                : b_val,
        'add_sub'          : totals['add_sub'],
        'mul_div'          : totals['mul_div'],
        'pow'              : totals['pow'],
        'math_calls'       : totals['calls'],
        'n_math_calls'     : n_calls,
        'Nop'              : nop,
        'total_ops_comment': top_comment,
    }
    if verbose:
        result['_verbose'] = [
            {'line': ln, 'ops': ops, 'src': src}
            for ln, ops, src in verbose_rows
        ]
    return result


# ---------------------------------------------------------------------------
# Pretty printing helpers
# ---------------------------------------------------------------------------

def _fmt_result(r: dict) -> str:
    calls_str = ', '.join(f'{k}×{v}' for k, v in sorted(r['math_calls'].items()))
    comment   = (f'  [comment: total_ops={r["total_ops_comment"]}]'
                 if r['total_ops_comment'] is not None else '')
    return (
        f'  Nop      = {r["Nop"]}\n'
        f'  add_sub  = {r["add_sub"]}\n'
        f'  mul_div  = {r["mul_div"]}\n'
        f'  pow      = {r["pow"]}\n'
        f'  math     = {r["n_math_calls"]}  ({calls_str})'
        + comment
    )


def _csv_row(r: dict, header: bool = False) -> str:
    cols = ['file', 'm', 'a', 'b', 'Nop', 'add_sub', 'mul_div', 'pow', 'n_math_calls']
    if header:
        return ','.join(cols)
    return ','.join(
        str(r.get(c, '')) for c in cols
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description='Count single-grid-point arithmetic operations (Nop) in '
                    'Julia filter .jl files.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument('files', nargs='*', metavar='FILE.jl',
                    help='Julia source files to analyse.')
    ap.add_argument('--glob', type=str, default=None,
                    help='Shell glob pattern for .jl files '
                         '(e.g. "julia_filter_m*.jl").')
    ap.add_argument('--json', type=str, default=None, metavar='OUT.json',
                    help='Write results to JSON file.')
    ap.add_argument('--csv', action='store_true',
                    help='Print results as CSV table.')
    ap.add_argument('--verbose', '-v', action='store_true',
                    help='Show per-line operation breakdown.')
    ap.add_argument('--sort', choices=['Nop', 'm', 'file'], default='file',
                    help='Sort output by this field  [default: file]')
    args = ap.parse_args()

    # Collect file paths
    paths: list[Path] = []
    for f in args.files:
        p = Path(f)
        if p.exists():
            paths.append(p)
        else:
            # may be an unexpanded glob from the shell
            matched = sorted(Path('.').glob(f))
            if matched:
                paths.extend(matched)
            else:
                print(f'Warning: {f!r} not found, skipping.', file=sys.stderr)

    if args.glob:
        paths.extend(sorted(Path('.').glob(args.glob)))

    paths = list(dict.fromkeys(paths))   # deduplicate, preserve order

    if not paths:
        ap.error('No .jl files found. Pass file arguments or use --glob.')

    # Analyse
    results = [analyze_file(p, verbose=args.verbose) for p in paths]

    # Sort
    key = args.sort
    results.sort(key=lambda r: (r.get(key) is None, r.get(key, '')))

    # ── print ─────────────────────────────────────────────────────────────────
    if args.csv:
        print(_csv_row(results[0], header=True))
        for r in results:
            print(_csv_row(r))
    else:
        for r in results:
            fn   = Path(r['file']).name
            tag  = (f'm={r["m"]}  a={r["a"]}  b={r["b"]}'
                    if r['m'] is not None else fn)
            print(f'\n{fn}  [{tag}]')
            print(_fmt_result(r))
            if args.verbose and '_verbose' in r:
                print('  Per-line breakdown:')
                for row in r['_verbose']:
                    ops = row['ops']
                    n   = (ops['add_sub'] + ops['mul_div'] + ops['pow']
                           + sum(ops['calls'].values()))
                    print(f'    L{row["line"]:4d} [{n:3d} ops] {row["src"][:90]}')

    # ── JSON output ───────────────────────────────────────────────────────────
    if args.json:
        out = []
        for r in results:
            rec = {k: v for k, v in r.items() if not k.startswith('_')}
            out.append(rec)
        Path(args.json).write_text(json.dumps(out, indent=2))
        print(f'\nResults → {args.json}')


if __name__ == '__main__':
    main()
