"""rbf_core — backward-compatible thin wrapper over rbf_code/.

All public names are preserved so existing callers need no changes.
"""
# ruff: noqa: F401, F403
from rbf_code import *  # noqa: F401,F403
from rbf_code import (
    Array,
    _raise_on_nonfinite,
    _periodic_delta_frac,
    KERNELS_ALL,
    KERNEL_GROUPS,
    RBFConfig,
    RBFProblem,
    IterationRecord,
    _wrap_frac,
    _unique_rows_mod1,
    _unique_cart_rows,
    _periodic_diff,
    _periodic_dist,
    _build_uniform_frac_grid,
    _estimate_grad_laplacian_uniform,
    _adaptive_accept_and_filter_periodic,
    _greedy_filter_by_dmin_periodic,
    _make_unit_cube_surface,
    _CONV_CELL_IN_FRAC_DEFAULT,
    _CONV_CELL_AS_FRAC_DEFAULT,
    _FCC_OFFSETS_FRAC,
    _LEVEL3_BASE_FRAC_DEFAULT,
    generate_nodes,
    make_grid_points,
    _make_icosphere,
    generate_sphere_nodes,
    _filter_close_points,
    generate_atom_augmented_nodes,
    _generate_shifted_refined_fcc_frac,
    _poisson_like_periodic,
    generate_conv_cell_nodes,
    relative_laplacian_error,
    build_hamiltonian_matrix,
    compute_node_quality,
    weight_matrix_conv_cell_reuse,
    weight_matrix_ball_fingerprint,
    read_cube_file,
    read_cube_atoms,
    build_qd_problem,
    build_problem,
    solve_lowest_eigenvalues,
    _ho_exact_levels,
    sweep_rbf_kernels,
    sweep_stencil_eps,
    iterate_hamiltonian,
)
