# H^n=1 auto-generated by symbolic_code.julia_codegen
# n_cos_groups=0  n_sin_groups=1

@inline function _poly_s_n1_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return 0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.5 * x ^ 2 + 0.5 * y ^ 2 + 0.5 * z ^ 2
end

@inline function _exp_s_n1_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end
