# H^n=0 auto-generated by symbolic_code.julia_codegen
# n_cos_groups=0  n_sin_groups=1

@inline function _poly_s_n0_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return 1
end

@inline function _exp_s_n0_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end
