# H^n=2 auto-generated by symbolic_code.julia_codegen
# n_cos_groups=1  n_sin_groups=1

@inline function _poly_c_n2_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return -kx * x - ky * y - kz * z
end

@inline function _exp_c_n2_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

@inline function _poly_s_n2_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return kx ^ 2 * (0.25 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2) + ky ^ 2 * (0.25 * ky ^ 2 + 0.5 * kz ^ 2) + 0.25 * kz ^ 4 + x ^ 2 * (0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.25 * x ^ 2 + 0.5 * y ^ 2 + 0.5 * z ^ 2) + y ^ 2 * (0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.25 * y ^ 2 + 0.5 * z ^ 2) + z ^ 2 * (0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.25 * z ^ 2) - 1.5
end

@inline function _exp_s_n2_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end
