# H^n=3 auto-generated by symbolic_code.julia_codegen
# n_cos_groups=1  n_sin_groups=1

@inline function _poly_c_n3_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return x * (-1.5 * kx * y ^ 2 - 1.5 * kx * z ^ 2 + kx * (-1.5 * kx ^ 2 - 1.5 * ky ^ 2 - 1.5 * kz ^ 2) + x * (-1.5 * kx * x - 1.5 * ky * y - 1.5 * kz * z)) + y * (-1.5 * kx ^ 2 * ky - 1.5 * ky * z ^ 2 + ky * (-1.5 * ky ^ 2 - 1.5 * kz ^ 2) + y * (-1.5 * ky * y - 1.5 * kz * z)) + z * (-1.5 * kx ^ 2 * kz - 1.5 * ky ^ 2 * kz - 1.5 * kz ^ 3 - 1.5 * kz * z ^ 2)
end

@inline function _exp_c_n3_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

@inline function _poly_s_n3_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return kx ^ 2 * (kx ^ 2 * (0.125 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 - 3.25) + ky ^ 2 * (ky ^ 2 * (0.125 * ky ^ 2 + 0.375 * kz ^ 2) + 0.375 * kz ^ 4 - 3.25) + kz ^ 2 * (0.125 * kz ^ 4 - 3.25) + x ^ 2 * (kx ^ 2 * (0.375 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 + x ^ 2 * (0.375 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2 + 0.125 * x ^ 2 + 0.375 * y ^ 2 + 0.375 * z ^ 2) + y ^ 2 * (0.75 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2 + 0.375 * y ^ 2 + 0.75 * z ^ 2) + z ^ 2 * (0.75 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2 + 0.375 * z ^ 2) - 3.25) + y ^ 2 * (kx ^ 2 * (0.375 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 + y ^ 2 * (0.375 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2 + 0.125 * y ^ 2 + 0.375 * z ^ 2) + z ^ 2 * (0.75 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2 + 0.375 * z ^ 2) - 3.25) + z ^ 2 * (kx ^ 2 * (0.375 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 + z ^ 2 * (0.375 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2 + 0.125 * z ^ 2) - 3.25)
end

@inline function _exp_s_n3_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end
