# Auto-generated by symbolic_code.julia_codegen — DO NOT EDIT
# f(H)·ψ = Σ_n c_n H^n·ψ, coefficients supplied at runtime.
#
# Polynomial order: m = 3
#
# Usage:
#   julia julia_Hn_m{m}.jl grid.bin kvals.bin out.bin N n_waves c0 c1 … cm
#
# Stdout (last line): JSON {warmup_s, eval_s, n_eval_waves}

@inline function _poly_s_n0_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return 1
end

@inline function _exp_s_n0_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

@inline function _poly_s_n1_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return 0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.5 * x ^ 2 + 0.5 * y ^ 2 + 0.5 * z ^ 2
end

@inline function _exp_s_n1_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

@inline function _poly_c_n2_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return -kx * x - ky * y - kz * z
end

@inline function _exp_c_n2_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

@inline function _poly_s_n2_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return kx ^ 2 * (0.25 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2) + ky ^ 2 * (0.25 * ky ^ 2 + 0.5 * kz ^ 2) + 0.25 * kz ^ 4 + x ^ 2 * (0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.25 * x ^ 2 + 0.5 * y ^ 2 + 0.5 * z ^ 2) + y ^ 2 * (0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.25 * y ^ 2 + 0.5 * z ^ 2) + z ^ 2 * (0.5 * kx ^ 2 + 0.5 * ky ^ 2 + 0.5 * kz ^ 2 + 0.25 * z ^ 2) - 1.5
end

@inline function _exp_s_n2_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

@inline function _poly_c_n3_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return x * (-1.5 * kx * y ^ 2 - 1.5 * kx * z ^ 2 + kx * (-1.5 * kx ^ 2 - 1.5 * ky ^ 2 - 1.5 * kz ^ 2) + x * (-1.5 * kx * x - 1.5 * ky * y - 1.5 * kz * z)) + y * (-1.5 * kx ^ 2 * ky - 1.5 * ky * z ^ 2 + ky * (-1.5 * ky ^ 2 - 1.5 * kz ^ 2) + y * (-1.5 * ky * y - 1.5 * kz * z)) + z * (-1.5 * kx ^ 2 * kz - 1.5 * ky ^ 2 * kz - 1.5 * kz ^ 3 - 1.5 * kz * z ^ 2)
end

@inline function _exp_c_n3_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

@inline function _poly_s_n3_g0(x::Float64,y::Float64,z::Float64,kx::Float64,ky::Float64,kz::Float64)::Float64
    return kx ^ 2 * (kx ^ 2 * (0.125 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 - 3.25) + ky ^ 2 * (ky ^ 2 * (0.125 * ky ^ 2 + 0.375 * kz ^ 2) + 0.375 * kz ^ 4 - 3.25) + kz ^ 2 * (0.125 * kz ^ 4 - 3.25) + x ^ 2 * (kx ^ 2 * (0.375 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 + x ^ 2 * (0.375 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2 + 0.125 * x ^ 2 + 0.375 * y ^ 2 + 0.375 * z ^ 2) + y ^ 2 * (0.75 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2 + 0.375 * y ^ 2 + 0.75 * z ^ 2) + z ^ 2 * (0.75 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2 + 0.375 * z ^ 2) - 3.25) + y ^ 2 * (kx ^ 2 * (0.375 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 + y ^ 2 * (0.375 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2 + 0.125 * y ^ 2 + 0.375 * z ^ 2) + z ^ 2 * (0.75 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2 + 0.375 * z ^ 2) - 3.25) + z ^ 2 * (kx ^ 2 * (0.375 * kx ^ 2 + 0.75 * ky ^ 2 + 0.75 * kz ^ 2) + ky ^ 2 * (0.375 * ky ^ 2 + 0.75 * kz ^ 2) + 0.375 * kz ^ 4 + z ^ 2 * (0.375 * kx ^ 2 + 0.375 * ky ^ 2 + 0.375 * kz ^ 2 + 0.125 * z ^ 2) - 3.25)
end

@inline function _exp_s_n3_g0(x::Float64,y::Float64,z::Float64)::Float64
    return 1
end

function eval_one_wave!(out::AbstractVector{Float64},
                        X::Vector{Float64},Y::Vector{Float64},Z::Vector{Float64},
                        kx::Float64,ky::Float64,kz::Float64,b::Float64,
                        c::Vector{Float64},
                        phase::Vector{Float64},cos_p::Vector{Float64},sin_p::Vector{Float64})
    @. phase = kx*X + ky*Y + kz*Z + b
    @. cos_p = cos(phase)
    @. sin_p = sin(phase)
    @inbounds for i in eachindex(X)
        xi,yi,zi = X[i],Y[i],Z[i]
        _sum_cos = 0.0
        _sum_cos += c[3] * _exp_c_n2_g0(xi,yi,zi) * _poly_c_n2_g0(xi,yi,zi,kx,ky,kz)
        _sum_cos += c[4] * _exp_c_n3_g0(xi,yi,zi) * _poly_c_n3_g0(xi,yi,zi,kx,ky,kz)
        _sum_sin = 0.0
        _sum_sin += c[1] * _exp_s_n0_g0(xi,yi,zi) * _poly_s_n0_g0(xi,yi,zi,kx,ky,kz)
        _sum_sin += c[2] * _exp_s_n1_g0(xi,yi,zi) * _poly_s_n1_g0(xi,yi,zi,kx,ky,kz)
        _sum_sin += c[3] * _exp_s_n2_g0(xi,yi,zi) * _poly_s_n2_g0(xi,yi,zi,kx,ky,kz)
        _sum_sin += c[4] * _exp_s_n3_g0(xi,yi,zi) * _poly_s_n3_g0(xi,yi,zi,kx,ky,kz)
        out[i] = cos_p[i]*_sum_cos + sin_p[i]*_sum_sin
    end
end

function main()
    length(ARGS) == 9 || error(
        "Usage: julia script.jl grid.bin kvals.bin out.bin N n_waves c0…c3")
    grid_file  = ARGS[1]
    kvals_file = ARGS[2]
    out_file   = ARGS[3]
    N          = parse(Int, ARGS[4])
    n_waves    = parse(Int, ARGS[5])
    c = [parse(Float64, ARGS[5+j]) for j in 1:4]

    buf = Vector{Float64}(undef, 3*N)
    open(grid_file,"r") do io; read!(io, buf); end
    X = buf[1:N]; Y = buf[N+1:2N]; Z = buf[2N+1:3N]

    kb = Vector{Float64}(undef, 4*n_waves)
    open(kvals_file,"r") do io; read!(io, kb); end

    out   = Vector{Float64}(undef, N*n_waves)
    phase = Vector{Float64}(undef, N)
    cos_p = Vector{Float64}(undef, N)
    sin_p = Vector{Float64}(undef, N)

    t_warmup = @elapsed eval_one_wave!(
        @view(out[1:N]), X, Y, Z,
        kb[1], kb[2], kb[3], kb[4], c, phase, cos_p, sin_p)

    t_eval = @elapsed for iw in 1:n_waves-1
        ofs = iw*N + 1
        kid = iw*4 + 1
        eval_one_wave!(@view(out[ofs:ofs+N-1]), X, Y, Z,
                       kb[kid], kb[kid+1], kb[kid+2], kb[kid+3],
                       c, phase, cos_p, sin_p)
    end

    open(out_file,"w") do io; write(io, out); end

    n_eval = max(n_waves-1, 1)
    println("{\"warmup_s\": $t_warmup, \"eval_s\": $t_eval, \"n_eval_waves\": $n_eval}")
end

main()